### ISSUE TITLE
fatal exception if I tap "Test Register" button"

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-android-agent#72]
If I install the application, launch it and tap "Test Register" I the app crashes. 

Version 0.99.1 of the rewritten app.

Backtrace:
```
E/AndroidRuntime( 7732): FATAL EXCEPTION: IntentService[MQTTService]
E/AndroidRuntime( 7732): Process: org.flyve.mdm.agent, PID: 7732
E/AndroidRuntime( 7732): java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
E/AndroidRuntime( 7732): 	at org.flyve.mdm.agent.services.MQTTService.connect(MQTTService.java:121)
E/AndroidRuntime( 7732): 	at org.flyve.mdm.agent.services.MQTTService.onHandleIntent(MQTTService.java:84)
E/AndroidRuntime( 7732): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime( 7732): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7732): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7732): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/ActivityManager(  974):   Force finishing activity 1 org.flyve.mdm.agent/.MainActivity
```

**Comment by rafaelje** [comment]
This button was remove
